services:
  alpined:
    image: alpine:latest
    container_name: alpined
    hostname: alpined
    ports:
      - "23:22"
      - "21023:22"
    environment:
      - USER="c"
      - PASSWORD="22111357"
      - PASS="22111357"
      - ROOT_PASSWORD="22111357"
    # command:
    #   # - "/bin/sh" 
    #   # - "-c"
    #   # - |
    #   #   addgroup c root && adduser -S -G root c && echo ${PASS} | chpasswd && sshd
    #     journalctl -fu alpined > /home/c/Code/docker/alpined/logg.dool &  
    volumes:
      - alpined-data:/
    logging:
      driver: "json-file"
      options:
        max-size: "20000000k"
        max-file: "10000000"
    networks:
      - open-net

networks:

  open-net:
    driver: bridge
    attachable: true
    name : open-net

volumes:
  alpined-data:
    driver: local
    driver_opts:
      type: none  
      device: /home/c/Code/docker/alpined
      o: bind
    name: alpined-data